"""USA — US Census 4 regions (mapped from 52 states), SOC 22-group occupation."""
from persona_pipeline.mappings._base import (
    CountryMappings, REGION, AGE_GEN, SEX, OCCUPATION_GROUP,
)


# US Census Bureau 4 regions.
STATE_TO_REGION: dict[str, str] = {
    # Northeast
    "CT": "Northeast", "ME": "Northeast", "MA": "Northeast", "NH": "Northeast",
    "NJ": "Northeast", "NY": "Northeast", "PA": "Northeast", "RI": "Northeast",
    "VT": "Northeast",
    # Midwest
    "IL": "Midwest", "IN": "Midwest", "IA": "Midwest", "KS": "Midwest",
    "MI": "Midwest", "MN": "Midwest", "MO": "Midwest", "NE": "Midwest",
    "ND": "Midwest", "OH": "Midwest", "SD": "Midwest", "WI": "Midwest",
    # South
    "AL": "South", "AR": "South", "DE": "South", "FL": "South",
    "GA": "South", "KY": "South", "LA": "South", "MD": "South",
    "MS": "South", "NC": "South", "OK": "South", "SC": "South",
    "TN": "South", "TX": "South", "VA": "South", "WV": "South",
    "DC": "South",
    # West
    "AK": "West", "AZ": "West", "CA": "West", "CO": "West",
    "HI": "West", "ID": "West", "MT": "West", "NV": "West",
    "NM": "West", "OR": "West", "UT": "West", "WA": "West", "WY": "West",
    # Territories — separate but include
    "PR": "Territory", "VI": "Territory", "GU": "Territory",
    "AS": "Territory", "MP": "Territory",
}


# SOC 2018 Major Groups (10 + Military). Free-text occupation → group.
# Keywords are substring-matched against the USA dataset's snake_case job names.
SOC_GROUPS: dict[str, list[str]] = {
    "Management": ["manager", "executive", "chief_executive", "ceo", "cfo", "director",
                   "supervisor", "administrator", "legislator"],
    "Business and Financial": ["analyst", "accountant", "auditor", "financial",
                               "buyer", "loan", "tax_preparer", "appraiser",
                               "human_resources", "fundraiser"],
    "Computer and Mathematical": ["computer", "software", "programmer", "developer",
                                  "data_scientist", "information_research",
                                  "mathematician", "actuary", "statistician",
                                  "web", "network"],
    "Architecture and Engineering": ["architect", "engineer", "engineering",
                                     "drafter", "surveyor"],
    "Life, Physical, and Social Science": ["scientist", "biologist", "chemist",
                                           "physicist", "geologist", "psychologist",
                                           "sociologist", "researcher"],
    "Community and Social Service": ["social_worker", "counselor", "clergy",
                                     "community", "social_and_human"],
    "Legal": ["lawyer", "judge", "paralegal", "legal", "law_clerk"],
    "Education": ["teacher", "professor", "instructor", "tutor", "librarian",
                  "school", "education", "kindergarten", "elementary",
                  "secondary", "postsecondary"],
    "Arts, Design, Entertainment, Sports, and Media": ["artist", "designer",
                                                       "musician", "actor",
                                                       "writer", "editor",
                                                       "photographer", "athlete",
                                                       "dancer", "reporter",
                                                       "broadcast", "media"],
    "Healthcare Practitioners": ["physician", "doctor", "nurse", "pharmacist",
                                 "dentist", "veterinarian", "therapist",
                                 "surgeon", "registered_nurse", "healthcare"],
    "Healthcare Support": ["nursing_assistant", "home_health", "medical_assistant",
                           "orderly", "phlebotomist", "occupational_therapy_assistant"],
    "Protective Service": ["police", "firefighter", "security", "correctional",
                           "detective", "officer", "guard"],
    "Food Preparation and Serving": ["food", "cook", "chef", "waiter", "waitress",
                                     "bartender", "fast_food", "host", "hostess",
                                     "dishwasher", "counter_worker"],
    "Building and Grounds Cleaning": ["janitor", "cleaner", "groundskeeper",
                                      "housekeeping", "landscaping", "pest_control"],
    "Personal Care and Service": ["barber", "hairdresser", "childcare", "fitness",
                                  "personal_care", "funeral", "tour_guide"],
    "Sales": ["sales", "cashier", "retail", "telemarketer", "real_estate_agent",
              "wholesale", "insurance_sales"],
    "Office and Administrative Support": ["clerk", "secretary", "receptionist",
                                          "office", "data_entry", "billing",
                                          "shipping", "stock", "dispatcher",
                                          "administrative_assistant"],
    "Farming, Fishing, and Forestry": ["farmer", "rancher", "fisher", "forest",
                                       "agricultural", "logging"],
    "Construction and Extraction": ["construction", "carpenter", "electrician",
                                    "plumber", "mason", "roofer", "painter",
                                    "miner", "drilling", "pipefitter"],
    "Installation, Maintenance, and Repair": ["mechanic", "repair", "installer",
                                              "maintenance", "technician_repair"],
    "Production": ["assembler", "machinist", "welder", "operator_production",
                   "fabricator", "production_worker", "tool_and_die"],
    "Transportation and Material Moving": ["driver", "truck", "taxi", "bus",
                                           "pilot", "aircraft", "transport",
                                           "delivery", "courier",
                                           "material_moving", "warehouse_worker",
                                           "laborer", "freight"],
    "Military": ["military", "armed_forces", "soldier", "marine", "navy",
                 "air_force", "national_guard"],
    "Not in Workforce": ["not_in_workforce", "no_occupation", "unemployed",
                         "homemaker", "retired", "student"],
}


MAPPINGS = CountryMappings(
    country="USA",
    locale="en",
    hf_split="train",
    axes=[REGION, AGE_GEN, SEX, OCCUPATION_GROUP],
    persona_columns={
        "persona": "[Summary]",
        "professional_persona": "[Profession]",
        "sports_persona": "[Sports]",
        "arts_persona": "[Arts]",
        "travel_persona": "[Travel]",
        "culinary_persona": "[Culinary]",
    },
    region_source_col="state",
    region_map=STATE_TO_REGION,
    occupation_source_col="occupation",
    occupation_groups=SOC_GROUPS,
    region_keywords={
        "Northeast": ["northeast", "new york", "boston", "philadelphia",
                      "ny", "nj", "ma", "ct", "pa"],
        "Midwest": ["midwest", "chicago", "detroit", "minneapolis", "il", "mi",
                    "oh", "wi", "mn", "in"],
        "South": ["south", "southern", "texas", "florida", "atlanta", "dallas",
                  "houston", "miami", "tx", "fl", "ga", "nc", "va", "dc"],
        "West": ["west", "california", "los angeles", "san francisco", "seattle",
                 "denver", "ca", "wa", "or", "co", "az", "nv"],
        "Territory": ["puerto rico", "guam", "virgin islands", "samoa"],
    },
    age_gen_keywords={
        "young": ["young", "youth", "youthful", "20s", "early 30s", "millennial"],
        "middle_aged": ["middle", "middle-aged", "30s", "40s", "50s", "midlife"],
        "elderly": ["elderly", "old", "senior", "60s", "70s", "80s", "retiree", "boomer"],
    },
    sex_keywords={
        "Male": ["male", "man", "men", "guy", "boy"],
        "Female": ["female", "woman", "women", "girl", "lady"],
    },
    occupation_keywords={
        # Natural-language queries don't use snake_case, so keywords are space-separated.
        "Management": ["manager", "executive", "ceo", "director", "supervisor"],
        "Business and Financial": ["analyst", "accountant", "financial"],
        "Computer and Mathematical": ["software", "programmer", "developer", "engineer software", "data scientist"],
        "Architecture and Engineering": ["architect", "engineer"],
        "Life, Physical, and Social Science": ["scientist", "researcher"],
        "Community and Social Service": ["social worker", "counselor"],
        "Legal": ["lawyer", "attorney", "paralegal"],
        "Education": ["teacher", "professor", "tutor", "librarian"],
        "Arts, Design, Entertainment, Sports, and Media": ["artist", "designer", "musician", "writer", "athlete"],
        "Healthcare Practitioners": ["doctor", "nurse", "pharmacist", "physician", "therapist"],
        "Healthcare Support": ["nursing assistant", "medical assistant"],
        "Protective Service": ["police", "firefighter", "security guard"],
        "Food Preparation and Serving": ["cook", "chef", "waiter", "bartender"],
        "Building and Grounds Cleaning": ["janitor", "cleaner"],
        "Personal Care and Service": ["barber", "hairdresser"],
        "Sales": ["sales", "cashier", "retail"],
        "Office and Administrative Support": ["clerk", "secretary", "receptionist", "office worker"],
        "Farming, Fishing, and Forestry": ["farmer", "rancher", "fisher"],
        "Construction and Extraction": ["construction worker", "carpenter", "electrician", "plumber"],
        "Installation, Maintenance, and Repair": ["mechanic", "technician"],
        "Production": ["assembler", "welder", "factory worker"],
        "Transportation and Material Moving": ["driver", "truck driver", "delivery", "warehouse"],
        "Military": ["soldier", "marine", "military"],
        "Not in Workforce": ["unemployed", "homemaker", "retired", "student"],
    },
)
